//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCbansach.ProductService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.IProduct")]
    public interface IProduct {
        
        // CODEGEN: Parameter 'findAllResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelOf_Product/findAll", ReplyAction="http://tempuri.org/IModelOf_Product/findAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCbansach.ProductService.findAllResponse findAll(MVCbansach.ProductService.findAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelOf_Product/findAll", ReplyAction="http://tempuri.org/IModelOf_Product/findAllResponse")]
        System.Threading.Tasks.Task<MVCbansach.ProductService.findAllResponse> findAllAsync(MVCbansach.ProductService.findAllRequest request);
        
        // CODEGEN: Parameter 'findByIdResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelOf_Product/findById", ReplyAction="http://tempuri.org/IModelOf_Product/findByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCbansach.ProductService.findByIdResponse findById(MVCbansach.ProductService.findByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelOf_Product/findById", ReplyAction="http://tempuri.org/IModelOf_Product/findByIdResponse")]
        System.Threading.Tasks.Task<MVCbansach.ProductService.findByIdResponse> findByIdAsync(MVCbansach.ProductService.findByIdRequest request);
        
        // CODEGEN: Parameter 'entity' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelOf_Product/insert", ReplyAction="http://tempuri.org/IModelOf_Product/insertResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCbansach.ProductService.insertResponse insert(MVCbansach.ProductService.insertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelOf_Product/insert", ReplyAction="http://tempuri.org/IModelOf_Product/insertResponse")]
        System.Threading.Tasks.Task<MVCbansach.ProductService.insertResponse> insertAsync(MVCbansach.ProductService.insertRequest request);
        
        // CODEGEN: Parameter 'entity' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelOf_Product/update", ReplyAction="http://tempuri.org/IModelOf_Product/updateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCbansach.ProductService.updateResponse update(MVCbansach.ProductService.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelOf_Product/update", ReplyAction="http://tempuri.org/IModelOf_Product/updateResponse")]
        System.Threading.Tasks.Task<MVCbansach.ProductService.updateResponse> updateAsync(MVCbansach.ProductService.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelOf_Product/delete", ReplyAction="http://tempuri.org/IModelOf_Product/deleteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool delete(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelOf_Product/delete", ReplyAction="http://tempuri.org/IModelOf_Product/deleteResponse")]
        System.Threading.Tasks.Task<bool> deleteAsync(long id);
        
        // CODEGEN: Parameter 'findProuctsByCategoryResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/findProuctsByCategory", ReplyAction="http://tempuri.org/IProduct/findProuctsByCategoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCbansach.ProductService.findProuctsByCategoryResponse findProuctsByCategory(MVCbansach.ProductService.findProuctsByCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/findProuctsByCategory", ReplyAction="http://tempuri.org/IProduct/findProuctsByCategoryResponse")]
        System.Threading.Tasks.Task<MVCbansach.ProductService.findProuctsByCategoryResponse> findProuctsByCategoryAsync(MVCbansach.ProductService.findProuctsByCategoryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BookStoreService.EF")]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> categoryField;
        
        private bool categoryFieldSpecified;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private bool createdAtFieldSpecified;
        
        private string createdByField;
        
        private string descriptionField;
        
        private System.Xml.XmlElement descriptionXMLField;
        
        private System.Nullable<System.DateTime> modifiedAtField;
        
        private bool modifiedAtFieldSpecified;
        
        private string modifiedByField;
        
        private string moreImagesField;
        
        private string nameField;
        
        private System.Nullable<decimal> priceField;
        
        private bool priceFieldSpecified;
        
        private System.Nullable<int> promotionField;
        
        private bool promotionFieldSpecified;
        
        private System.Nullable<decimal> promotionPriceField;
        
        private bool promotionPriceFieldSpecified;
        
        private System.Nullable<int> quantityField;
        
        private bool quantityFieldSpecified;
        
        private System.Nullable<bool> showOnHomeField;
        
        private bool showOnHomeFieldSpecified;
        
        private System.Nullable<bool> statusField;
        
        private bool statusFieldSpecified;
        
        private string thumbnailField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategorySpecified {
            get {
                return this.categoryFieldSpecified;
            }
            set {
                this.categoryFieldSpecified = value;
                this.RaisePropertyChanged("CategorySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedAtSpecified {
            get {
                return this.createdAtFieldSpecified;
            }
            set {
                this.createdAtFieldSpecified = value;
                this.RaisePropertyChanged("CreatedAtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Xml.XmlElement DescriptionXML {
            get {
                return this.descriptionXMLField;
            }
            set {
                this.descriptionXMLField = value;
                this.RaisePropertyChanged("DescriptionXML");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> ModifiedAt {
            get {
                return this.modifiedAtField;
            }
            set {
                this.modifiedAtField = value;
                this.RaisePropertyChanged("ModifiedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedAtSpecified {
            get {
                return this.modifiedAtFieldSpecified;
            }
            set {
                this.modifiedAtFieldSpecified = value;
                this.RaisePropertyChanged("ModifiedAtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string MoreImages {
            get {
                return this.moreImagesField;
            }
            set {
                this.moreImagesField = value;
                this.RaisePropertyChanged("MoreImages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("PriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> Promotion {
            get {
                return this.promotionField;
            }
            set {
                this.promotionField = value;
                this.RaisePropertyChanged("Promotion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PromotionSpecified {
            get {
                return this.promotionFieldSpecified;
            }
            set {
                this.promotionFieldSpecified = value;
                this.RaisePropertyChanged("PromotionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> PromotionPrice {
            get {
                return this.promotionPriceField;
            }
            set {
                this.promotionPriceField = value;
                this.RaisePropertyChanged("PromotionPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PromotionPriceSpecified {
            get {
                return this.promotionPriceFieldSpecified;
            }
            set {
                this.promotionPriceFieldSpecified = value;
                this.RaisePropertyChanged("PromotionPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("QuantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<bool> ShowOnHome {
            get {
                return this.showOnHomeField;
            }
            set {
                this.showOnHomeField = value;
                this.RaisePropertyChanged("ShowOnHome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShowOnHomeSpecified {
            get {
                return this.showOnHomeFieldSpecified;
            }
            set {
                this.showOnHomeFieldSpecified = value;
                this.RaisePropertyChanged("ShowOnHomeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("StatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string Thumbnail {
            get {
                return this.thumbnailField;
            }
            set {
                this.thumbnailField = value;
                this.RaisePropertyChanged("Thumbnail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAll", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class findAllRequest {
        
        public findAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class findAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BookStoreService.EF")]
        public MVCbansach.ProductService.Product[] findAllResult;
        
        public findAllResponse() {
        }
        
        public findAllResponse(MVCbansach.ProductService.Product[] findAllResult) {
            this.findAllResult = findAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class findByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long id;
        
        public findByIdRequest() {
        }
        
        public findByIdRequest(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class findByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MVCbansach.ProductService.Product findByIdResult;
        
        public findByIdResponse() {
        }
        
        public findByIdResponse(MVCbansach.ProductService.Product findByIdResult) {
            this.findByIdResult = findByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insert", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MVCbansach.ProductService.Product entity;
        
        public insertRequest() {
        }
        
        public insertRequest(MVCbansach.ProductService.Product entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long insertResult;
        
        public insertResponse() {
        }
        
        public insertResponse(long insertResult) {
            this.insertResult = insertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MVCbansach.ProductService.Product entity;
        
        public updateRequest() {
        }
        
        public updateRequest(MVCbansach.ProductService.Product entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool updateResult;
        
        public updateResponse() {
        }
        
        public updateResponse(bool updateResult) {
            this.updateResult = updateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findProuctsByCategory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class findProuctsByCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public findProuctsByCategoryRequest() {
        }
        
        public findProuctsByCategoryRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findProuctsByCategoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class findProuctsByCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BookStoreService.EF")]
        public MVCbansach.ProductService.Product[] findProuctsByCategoryResult;
        
        public findProuctsByCategoryResponse() {
        }
        
        public findProuctsByCategoryResponse(MVCbansach.ProductService.Product[] findProuctsByCategoryResult) {
            this.findProuctsByCategoryResult = findProuctsByCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductChannel : MVCbansach.ProductService.IProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductClient : System.ServiceModel.ClientBase<MVCbansach.ProductService.IProduct>, MVCbansach.ProductService.IProduct {
        
        public ProductClient() {
        }
        
        public ProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCbansach.ProductService.findAllResponse MVCbansach.ProductService.IProduct.findAll(MVCbansach.ProductService.findAllRequest request) {
            return base.Channel.findAll(request);
        }
        
        public MVCbansach.ProductService.Product[] findAll() {
            MVCbansach.ProductService.findAllRequest inValue = new MVCbansach.ProductService.findAllRequest();
            MVCbansach.ProductService.findAllResponse retVal = ((MVCbansach.ProductService.IProduct)(this)).findAll(inValue);
            return retVal.findAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCbansach.ProductService.findAllResponse> MVCbansach.ProductService.IProduct.findAllAsync(MVCbansach.ProductService.findAllRequest request) {
            return base.Channel.findAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCbansach.ProductService.findAllResponse> findAllAsync() {
            MVCbansach.ProductService.findAllRequest inValue = new MVCbansach.ProductService.findAllRequest();
            return ((MVCbansach.ProductService.IProduct)(this)).findAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCbansach.ProductService.findByIdResponse MVCbansach.ProductService.IProduct.findById(MVCbansach.ProductService.findByIdRequest request) {
            return base.Channel.findById(request);
        }
        
        public MVCbansach.ProductService.Product findById(long id) {
            MVCbansach.ProductService.findByIdRequest inValue = new MVCbansach.ProductService.findByIdRequest();
            inValue.id = id;
            MVCbansach.ProductService.findByIdResponse retVal = ((MVCbansach.ProductService.IProduct)(this)).findById(inValue);
            return retVal.findByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCbansach.ProductService.findByIdResponse> MVCbansach.ProductService.IProduct.findByIdAsync(MVCbansach.ProductService.findByIdRequest request) {
            return base.Channel.findByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCbansach.ProductService.findByIdResponse> findByIdAsync(long id) {
            MVCbansach.ProductService.findByIdRequest inValue = new MVCbansach.ProductService.findByIdRequest();
            inValue.id = id;
            return ((MVCbansach.ProductService.IProduct)(this)).findByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCbansach.ProductService.insertResponse MVCbansach.ProductService.IProduct.insert(MVCbansach.ProductService.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public long insert(MVCbansach.ProductService.Product entity) {
            MVCbansach.ProductService.insertRequest inValue = new MVCbansach.ProductService.insertRequest();
            inValue.entity = entity;
            MVCbansach.ProductService.insertResponse retVal = ((MVCbansach.ProductService.IProduct)(this)).insert(inValue);
            return retVal.insertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCbansach.ProductService.insertResponse> MVCbansach.ProductService.IProduct.insertAsync(MVCbansach.ProductService.insertRequest request) {
            return base.Channel.insertAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCbansach.ProductService.insertResponse> insertAsync(MVCbansach.ProductService.Product entity) {
            MVCbansach.ProductService.insertRequest inValue = new MVCbansach.ProductService.insertRequest();
            inValue.entity = entity;
            return ((MVCbansach.ProductService.IProduct)(this)).insertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCbansach.ProductService.updateResponse MVCbansach.ProductService.IProduct.update(MVCbansach.ProductService.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public bool update(MVCbansach.ProductService.Product entity) {
            MVCbansach.ProductService.updateRequest inValue = new MVCbansach.ProductService.updateRequest();
            inValue.entity = entity;
            MVCbansach.ProductService.updateResponse retVal = ((MVCbansach.ProductService.IProduct)(this)).update(inValue);
            return retVal.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCbansach.ProductService.updateResponse> MVCbansach.ProductService.IProduct.updateAsync(MVCbansach.ProductService.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCbansach.ProductService.updateResponse> updateAsync(MVCbansach.ProductService.Product entity) {
            MVCbansach.ProductService.updateRequest inValue = new MVCbansach.ProductService.updateRequest();
            inValue.entity = entity;
            return ((MVCbansach.ProductService.IProduct)(this)).updateAsync(inValue);
        }
        
        public bool delete(long id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(long id) {
            return base.Channel.deleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCbansach.ProductService.findProuctsByCategoryResponse MVCbansach.ProductService.IProduct.findProuctsByCategory(MVCbansach.ProductService.findProuctsByCategoryRequest request) {
            return base.Channel.findProuctsByCategory(request);
        }
        
        public MVCbansach.ProductService.Product[] findProuctsByCategory(int id) {
            MVCbansach.ProductService.findProuctsByCategoryRequest inValue = new MVCbansach.ProductService.findProuctsByCategoryRequest();
            inValue.id = id;
            MVCbansach.ProductService.findProuctsByCategoryResponse retVal = ((MVCbansach.ProductService.IProduct)(this)).findProuctsByCategory(inValue);
            return retVal.findProuctsByCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCbansach.ProductService.findProuctsByCategoryResponse> MVCbansach.ProductService.IProduct.findProuctsByCategoryAsync(MVCbansach.ProductService.findProuctsByCategoryRequest request) {
            return base.Channel.findProuctsByCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCbansach.ProductService.findProuctsByCategoryResponse> findProuctsByCategoryAsync(int id) {
            MVCbansach.ProductService.findProuctsByCategoryRequest inValue = new MVCbansach.ProductService.findProuctsByCategoryRequest();
            inValue.id = id;
            return ((MVCbansach.ProductService.IProduct)(this)).findProuctsByCategoryAsync(inValue);
        }
    }
}
